name: proventi
description: "Pro20"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.24+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_messaging: ^15.1.6
  device_info_plus: ^10.1.2
  openapi_generator_annotations: 4.13.1
  provider: ^6.1.2
  vibration: ^2.0.1
  fluttertoast: ^8.2.8
  flutter_localization: ^0.2.1
  badges: ^3.1.2
  flutter_local_notifications: ^18.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.2.3
  file_picker: ^8.1.5
  lottie: ^3.1.0
  excel: ^4.0.3
  share_plus: ^7.2.2
  syncfusion_flutter_xlsio: ^25.2.3
  path_provider: ^2.1.4
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.8.0
  persistent_bottom_nav_bar: ^6.2.1
  awesome_bottom_bar: ^1.2.4
  cupertino_icons: ^1.0.6
  modal_bottom_sheet: ^3.0.0
  flutter_switch: ^0.3.2
  country_picker: ^2.0.27
  dash_chat_2: ^0.0.20
  awesome_dialog: ^3.2.1
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.0
  uuid: ^4.5.1
  super_tooltip: ^2.0.9
  shorebird_code_push: ^2.0.2
  super_cupertino_navigation_bar: ^2.1.2
  flutter_timer_countdown: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  openapi_generator: 4.13.1
  json_serializable: ^6.0.0
  build_runner: ^2.0.0
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
    - assets/sounds/
    - shorebird.yaml